apiVersion: v2
name: open-webui
description: Super simple LLM deployment
type: application
version: 0.1.0
appVersion: "0.6.14"
dependencies:
  - name: open-webui
    version: 6.20.0
    repository: https://helm.openwebui.com
