{{- if .Values.gateway.enabled -}} # Check if gateway is enabled
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Chart.Name }}-https-gateway
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: traefik
  listeners:
  - name: https
    protocol: HTTPS
    port: 8443
    hostname: {{ .Values.gateway.domain }}
    tls:
      mode: Terminate
      certificateRefs:
      - name: {{ .Chart.Name }}-tls
        namespace: {{ .Release.Namespace }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-tls
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ .Values.gateway.domain }}
  issuerRef:
    name: {{ coalesce .Values.gateway.issuer "cloudflare-issuer" }}
    kind: ClusterIssuer
  secretName: {{ .Chart.Name }}-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Chart.Name }}-https-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: {{ .Chart.Name }}-https-gateway
    namespace: {{ .Release.Namespace }}
  hostnames:
  - {{ .Values.gateway.domain }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.gateway.path }}
    backendRefs:
    - kind: Service
      name: {{ .Values.gateway.service }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.gateway.port }}
{{- end -}} # End of the if condition
